# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

if RUBY_VERSION =~ /1\.8/
  require 'rubygems'
  require 'require_relative'
  require 'ruby-debug'
end
require 'microstation'
#
DRAWING_DIR = File.join(File.dirname(__FILE__) , 'drawings')
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
end

def drawing_path(file)
  drawing = File.join(DRAWING_DIR,file)
  File.expand_path(drawing)
end

def open_existing_drawing(app)
  app.open_drawing( drawing_path('test.dgn'))
end


